// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AbrirchamadodereparovlidopeloproprietrioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void abrirchamadodereparovlidopeloproprietrio() {
    driver.get("https://localhost:44363/");
    driver.manage().window().setSize(new Dimension(1050, 700));
    driver.findElement(By.linkText("Chamados de Reparo")).click();
    driver.findElement(By.linkText("Create New")).click();
    driver.findElement(By.id("Id")).click();
    driver.findElement(By.id("Id")).click();
    {
      WebElement element = driver.findElement(By.id("Id"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("Id")).sendKeys("7");
    driver.findElement(By.id("Tipo")).click();
    driver.findElement(By.id("Tipo")).sendKeys("1");
    driver.findElement(By.id("Descricao")).click();
    driver.findElement(By.id("Descricao")).sendKeys("Obstrução na tubulação de água");
    driver.findElement(By.id("IdImovel")).click();
    driver.findElement(By.id("IdImovel")).sendKeys("2");
    driver.findElement(By.id("IdInquilino")).click();
    driver.findElement(By.id("IdInquilino")).sendKeys("2");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).click();
    driver.close();
  }
}
